// Decompiled by Jad v1.5.8e. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.geocities.com/kpdus/jad.html
// Decompiler options: braces fieldsfirst space lnc 

package org.apache.cordova;

import android.util.Log;
import android.webkit.CookieManager;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.channels.FileChannel;
import java.util.HashMap;
import java.util.Iterator;
import javax.net.ssl.HttpsURLConnection;
import org.apache.cordova.api.PluginResult;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

// Referenced classes of package org.apache.cordova:
//            FileTransfer, FileUploadResult, FileProgressResult

class val.objectId
    implements Runnable
{

    final FileTransfer this$0;
    final boolean val$chunkedMode;
    final questContext val$context;
    final String val$fileKey;
    final String val$fileName;
    final JSONObject val$headers;
    final String val$mimeType;
    final String val$objectId;
    final JSONObject val$params;
    final String val$source;
    final String val$target;
    final boolean val$trustEveryone;
    final URL val$url;
    final boolean val$useHttps;

    public void run()
    {
        if (!val$context.aborted) goto _L2; else goto _L1
_L1:
        return;
_L2:
        Object obj4;
        Object obj5;
        javax.net.ssl.SSLSocketFactory sslsocketfactory;
        Object obj7;
        Object obj8;
        javax.net.ssl.SSLSocketFactory sslsocketfactory1;
        Object obj9;
        javax.net.ssl.SSLSocketFactory sslsocketfactory2;
        Object obj10;
        javax.net.ssl.SSLSocketFactory sslsocketfactory3;
        Object obj11;
        Object obj12;
        Object obj13;
        Object obj14;
        Object obj15;
        Object obj16;
        Object obj17;
        Object obj18;
        Object obj19;
        byte abyte0[];
        byte abyte1[];
        Object obj20;
        Object obj21;
        Object obj22;
        Object obj23;
        Object obj24;
        Object obj25;
        Object obj26;
        Object obj27;
        Object obj28;
        int i;
        int k;
        int l;
        int i1;
        boolean flag;
        obj17 = null;
        obj18 = null;
        obj19 = null;
        abyte0 = null;
        obj = null;
        abyte1 = null;
        obj20 = null;
        obj21 = null;
        obj22 = null;
        obj23 = null;
        obj5 = null;
        obj24 = null;
        obj25 = null;
        obj26 = null;
        obj27 = null;
        obj28 = null;
        sslsocketfactory = null;
        flag = false;
        i1 = 0;
        i = -1;
        obj13 = obj;
        obj8 = abyte1;
        sslsocketfactory1 = obj24;
        obj14 = obj17;
        k = i;
        obj9 = obj20;
        sslsocketfactory2 = obj25;
        l = ((flag) ? 1 : 0);
        obj16 = obj18;
        obj11 = obj21;
        obj12 = obj26;
        obj15 = obj19;
        obj10 = obj22;
        sslsocketfactory3 = obj27;
        obj7 = abyte0;
        obj3 = obj23;
        obj4 = obj28;
        FileUploadResult fileuploadresult = new FileUploadResult();
        obj13 = obj;
        obj8 = abyte1;
        sslsocketfactory1 = obj24;
        obj14 = obj17;
        k = i;
        obj9 = obj20;
        sslsocketfactory2 = obj25;
        l = ((flag) ? 1 : 0);
        obj16 = obj18;
        obj11 = obj21;
        obj12 = obj26;
        obj15 = obj19;
        obj10 = obj22;
        sslsocketfactory3 = obj27;
        obj7 = abyte0;
        obj3 = obj23;
        obj4 = obj28;
        FileProgressResult fileprogressresult = new FileProgressResult();
        obj13 = obj;
        obj8 = abyte1;
        sslsocketfactory1 = obj24;
        obj14 = obj17;
        k = i;
        obj9 = obj20;
        sslsocketfactory2 = obj25;
        l = ((flag) ? 1 : 0);
        obj16 = obj18;
        obj11 = obj21;
        obj12 = obj26;
        obj15 = obj19;
        obj10 = obj22;
        sslsocketfactory3 = obj27;
        obj7 = abyte0;
        obj3 = obj23;
        obj4 = obj28;
        if (!val$useHttps) goto _L4; else goto _L3
_L3:
        obj13 = obj;
        obj8 = abyte1;
        sslsocketfactory1 = obj24;
        obj14 = obj17;
        k = i;
        obj9 = obj20;
        sslsocketfactory2 = obj25;
        l = ((flag) ? 1 : 0);
        obj16 = obj18;
        obj11 = obj21;
        obj12 = obj26;
        obj15 = obj19;
        obj10 = obj22;
        sslsocketfactory3 = obj27;
        obj7 = abyte0;
        obj3 = obj23;
        obj4 = obj28;
        if (val$trustEveryone) goto _L6; else goto _L5
_L5:
        obj13 = obj;
        obj8 = abyte1;
        sslsocketfactory1 = obj24;
        obj14 = obj17;
        k = i;
        obj9 = obj20;
        sslsocketfactory2 = obj25;
        l = ((flag) ? 1 : 0);
        obj16 = obj18;
        obj11 = obj21;
        obj12 = obj26;
        obj15 = obj19;
        obj10 = obj22;
        sslsocketfactory3 = obj27;
        obj7 = abyte0;
        obj3 = obj23;
        obj4 = obj28;
        obj = (HttpsURLConnection)val$url.openConnection();
_L11:
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((HttpURLConnection) (obj)).setDoInput(true);
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((HttpURLConnection) (obj)).setDoOutput(true);
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((HttpURLConnection) (obj)).setUseCaches(false);
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((HttpURLConnection) (obj)).setRequestMethod("POST");
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((HttpURLConnection) (obj)).setRequestProperty("Content-Type", "multipart/form-data;boundary=+++++");
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        obj17 = CookieManager.getInstance().getCookie(val$target);
        if (obj17 == null)
        {
            break MISSING_BLOCK_LABEL_919;
        }
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((HttpURLConnection) (obj)).setRequestProperty("Cookie", ((String) (obj17)));
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        obj17 = val$headers;
        if (obj17 == null)
        {
            break; /* Loop/switch isn't completed */
        }
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        obj16 = val$headers.keys();
_L8:
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        if (!((Iterator) (obj16)).hasNext())
        {
            break; /* Loop/switch isn't completed */
        }
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        obj17 = ((Iterator) (obj16)).next().toString();
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        obj12 = val$headers.optJSONArray(((String) (obj17)));
        obj11 = obj12;
        if (obj12 != null)
        {
            break MISSING_BLOCK_LABEL_1366;
        }
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        obj11 = new JSONArray();
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((JSONArray) (obj11)).put(val$headers.getString(((String) (obj17))));
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((HttpURLConnection) (obj)).setRequestProperty(((String) (obj17)), ((JSONArray) (obj11)).getString(0));
        int j = 1;
_L9:
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        if (j >= ((JSONArray) (obj11)).length()) goto _L8; else goto _L7
_L7:
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((HttpURLConnection) (obj)).addRequestProperty(((String) (obj17)), ((JSONArray) (obj11)).getString(j));
        j++;
          goto _L9
_L6:
        obj13 = obj;
        obj8 = abyte1;
        sslsocketfactory1 = obj24;
        obj14 = obj17;
        k = i;
        obj9 = obj20;
        sslsocketfactory2 = obj25;
        l = ((flag) ? 1 : 0);
        obj16 = obj18;
        obj11 = obj21;
        obj12 = obj26;
        obj15 = obj19;
        obj10 = obj22;
        sslsocketfactory3 = obj27;
        obj7 = abyte0;
        obj3 = obj23;
        obj4 = obj28;
        HttpsURLConnection httpsurlconnection = (HttpsURLConnection)val$url.openConnection();
        obj13 = obj;
        obj8 = abyte1;
        sslsocketfactory1 = obj24;
        obj14 = obj17;
        k = i;
        obj9 = obj20;
        sslsocketfactory2 = obj25;
        l = ((flag) ? 1 : 0);
        obj16 = obj18;
        obj11 = obj21;
        obj12 = obj26;
        obj15 = obj19;
        obj10 = obj22;
        sslsocketfactory3 = obj27;
        obj7 = abyte0;
        obj3 = obj23;
        obj4 = obj28;
        sslsocketfactory = FileTransfer.access$000(httpsurlconnection);
        obj13 = obj;
        obj8 = abyte1;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj17;
        k = i;
        obj9 = obj20;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj18;
        obj11 = obj21;
        obj12 = sslsocketfactory;
        obj15 = obj19;
        obj10 = obj22;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = abyte0;
        obj3 = obj23;
        obj4 = sslsocketfactory;
        obj5 = httpsurlconnection.getHostnameVerifier();
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj17;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj18;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj19;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = abyte0;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        httpsurlconnection.setHostnameVerifier(FileTransfer.access$100());
        obj = httpsurlconnection;
        continue; /* Loop/switch isn't completed */
_L4:
        obj13 = obj;
        obj8 = abyte1;
        sslsocketfactory1 = obj24;
        obj14 = obj17;
        k = i;
        obj9 = obj20;
        sslsocketfactory2 = obj25;
        l = ((flag) ? 1 : 0);
        obj16 = obj18;
        obj11 = obj21;
        obj12 = obj26;
        obj15 = obj19;
        obj10 = obj22;
        sslsocketfactory3 = obj27;
        obj7 = abyte0;
        obj3 = obj23;
        obj4 = obj28;
        obj = (HttpURLConnection)val$url.openConnection();
        if (true) goto _L11; else goto _L10
_L10:
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        obj17 = new StringBuilder();
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        obj11 = val$params.keys();
_L13:
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        if (!((Iterator) (obj11)).hasNext())
        {
            break MISSING_BLOCK_LABEL_2660;
        }
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        obj12 = ((Iterator) (obj11)).next();
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        if (String.valueOf(obj12).equals("headers")) goto _L13; else goto _L12
_L12:
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((StringBuilder) (obj17)).append("--").append("+++++").append("\r\n");
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((StringBuilder) (obj17)).append("Content-Disposition: form-data; name=\"").append(obj12.toString()).append('"');
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((StringBuilder) (obj17)).append("\r\n").append("\r\n");
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((StringBuilder) (obj17)).append(val$params.getString(obj12.toString()));
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((StringBuilder) (obj17)).append("\r\n");
          goto _L13
        JSONException jsonexception1;
        jsonexception1;
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        Log.e("FileTransfer", jsonexception1.getMessage(), jsonexception1);
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((StringBuilder) (obj17)).append("--").append("+++++").append("\r\n");
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((StringBuilder) (obj17)).append("Content-Disposition: form-data; name=\"").append(val$fileKey).append("\";");
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((StringBuilder) (obj17)).append(" filename=\"").append(val$fileName).append('"').append("\r\n");
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((StringBuilder) (obj17)).append("Content-Type: ").append(val$mimeType).append("\r\n").append("\r\n");
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        abyte1 = ((StringBuilder) (obj17)).toString().getBytes("UTF-8");
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        abyte0 = "\r\n--+++++--\r\n".getBytes("UTF-8");
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        obj19 = FileTransfer.access$200(FileTransfer.this, val$source);
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        int j1 = abyte1.length;
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        int k1 = abyte0.length;
        j = i;
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        if (!(obj19 instanceof FileInputStream))
        {
            break MISSING_BLOCK_LABEL_3631;
        }
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = i;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        j = (int)((FileInputStream)obj19).getChannel().size() + (j1 + k1);
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        fileprogressresult.setLengthComputable(true);
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        fileprogressresult.setTotal(j);
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        Log.d("FileTransfer", (new StringBuilder()).append("Content Length: ").append(j).toString());
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        if (!val$chunkedMode) goto _L15; else goto _L14
_L14:
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        if (android.os.DK_INT < 8) goto _L17; else goto _L16
_L16:
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        if (!val$useHttps) goto _L15; else goto _L17
_L23:
        if (i == 0) goto _L19; else goto _L18
_L18:
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((HttpURLConnection) (obj)).setChunkedStreamingMode(16384);
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((HttpURLConnection) (obj)).setRequestProperty("Transfer-Encoding", "chunked");
_L24:
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((HttpURLConnection) (obj)).connect();
        obj17 = null;
        i = i1;
        jsonexception1 = ((HttpURLConnection) (obj)).getOutputStream();
        obj17 = jsonexception1;
        i = i1;
        obj3 = val$context;
        obj17 = jsonexception1;
        i = i1;
        obj3;
        JVM INSTR monitorenter ;
        if (!val$context.aborted) goto _L21; else goto _L20
_L20:
        obj3;
        JVM INSTR monitorexit ;
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        FileTransfer.access$300(((java.io.Closeable) (obj19)));
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        FileTransfer.access$300(jsonexception1);
        synchronized (FileTransfer.access$600())
        {
            FileTransfer.access$600().remove(val$objectId);
        }
        if (obj != null && val$trustEveryone && val$useHttps)
        {
            obj = (HttpsURLConnection)obj;
            ((HttpsURLConnection) (obj)).setHostnameVerifier(((javax.net.ssl.HostnameVerifier) (obj5)));
            ((HttpsURLConnection) (obj)).setSSLSocketFactory(sslsocketfactory);
            return;
        }
          goto _L1
_L15:
        i = 0;
          goto _L22
_L36:
        i = 0;
          goto _L23
_L19:
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = ((flag) ? 1 : 0);
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        ((HttpURLConnection) (obj)).setFixedLengthStreamingMode(j);
          goto _L24
        obj;
        obj7 = obj13;
        obj3 = obj8;
        obj4 = sslsocketfactory1;
        obj5 = FileTransfer.access$500(FileTransfer.FILE_NOT_FOUND_ERR, val$source, val$target, ((java.net.URLConnection) (obj13)));
        obj7 = obj13;
        obj3 = obj8;
        obj4 = sslsocketfactory1;
        Log.e("FileTransfer", ((JSONObject) (obj5)).toString(), ((Throwable) (obj)));
        obj7 = obj13;
        obj3 = obj8;
        obj4 = sslsocketfactory1;
        val$context.sendPluginResult(new PluginResult(org.apache.cordova.api.atus.IO_EXCEPTION, ((JSONObject) (obj5))));
        synchronized (FileTransfer.access$600())
        {
            FileTransfer.access$600().remove(val$objectId);
        }
        if (obj13 == null || !val$trustEveryone || !val$useHttps) goto _L1; else goto _L25
_L25:
        obj = (HttpsURLConnection)obj13;
        ((HttpsURLConnection) (obj)).setHostnameVerifier(((javax.net.ssl.HostnameVerifier) (obj8)));
        ((HttpsURLConnection) (obj)).setSSLSocketFactory(sslsocketfactory1);
        return;
        obj;
        obj3;
        JVM INSTR monitorexit ;
        throw obj;
_L21:
        val$context.currentOutputStream = jsonexception1;
        obj3;
        JVM INSTR monitorexit ;
        obj17 = jsonexception1;
        i = i1;
        jsonexception1.write(abyte1);
        obj17 = jsonexception1;
        i = i1;
        k = 0 + abyte1.length;
        obj17 = jsonexception1;
        i = k;
        l = Math.min(((InputStream) (obj19)).available(), 16384);
        obj17 = jsonexception1;
        i = k;
        obj3 = new byte[l];
        obj17 = jsonexception1;
        i = k;
        l = ((InputStream) (obj19)).read(((byte []) (obj3)), 0, l);
        long l1 = 0L;
_L27:
        if (l <= 0)
        {
            break; /* Loop/switch isn't completed */
        }
        obj17 = jsonexception1;
        i = k;
        fileuploadresult.setBytesSent(k);
        obj17 = jsonexception1;
        i = k;
        jsonexception1.write(((byte []) (obj3)), 0, l);
        long l2;
        k += l;
        l2 = l1;
        if ((long)k <= 0x19000L + l1)
        {
            break MISSING_BLOCK_LABEL_4811;
        }
        l2 = k;
        obj17 = jsonexception1;
        i = k;
        Log.d("FileTransfer", (new StringBuilder()).append("Uploaded ").append(k).append(" of ").append(j).append(" bytes").toString());
        obj17 = jsonexception1;
        i = k;
        l = ((InputStream) (obj19)).read(((byte []) (obj3)), 0, Math.min(((InputStream) (obj19)).available(), 16384));
        obj17 = jsonexception1;
        i = k;
        fileprogressresult.setLoaded(k);
        obj17 = jsonexception1;
        i = k;
        obj4 = new PluginResult(org.apache.cordova.api.atus.OK, fileprogressresult.toJSONObject());
        obj17 = jsonexception1;
        i = k;
        ((PluginResult) (obj4)).setKeepCallback(true);
        obj17 = jsonexception1;
        i = k;
        val$context.sendPluginResult(((PluginResult) (obj4)));
        l1 = l2;
        if (true) goto _L27; else goto _L26
        jsonexception1;
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        FileTransfer.access$300(((java.io.Closeable) (obj19)));
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        FileTransfer.access$300(((java.io.Closeable) (obj17)));
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        throw jsonexception1;
        obj;
        obj7 = obj14;
        obj3 = obj9;
        obj4 = sslsocketfactory2;
        obj5 = FileTransfer.access$500(FileTransfer.CONNECTION_ERR, val$source, val$target, ((java.net.URLConnection) (obj14)));
        obj7 = obj14;
        obj3 = obj9;
        obj4 = sslsocketfactory2;
        Log.e("FileTransfer", ((JSONObject) (obj5)).toString(), ((Throwable) (obj)));
        obj7 = obj14;
        obj3 = obj9;
        obj4 = sslsocketfactory2;
        Log.e("FileTransfer", (new StringBuilder()).append("Failed after uploading ").append(l).append(" of ").append(k).append(" bytes.").toString());
        obj7 = obj14;
        obj3 = obj9;
        obj4 = sslsocketfactory2;
        val$context.sendPluginResult(new PluginResult(org.apache.cordova.api.atus.IO_EXCEPTION, ((JSONObject) (obj5))));
        synchronized (FileTransfer.access$600())
        {
            FileTransfer.access$600().remove(val$objectId);
        }
        if (obj14 == null || !val$trustEveryone || !val$useHttps) goto _L1; else goto _L28
_L28:
        obj = (HttpsURLConnection)obj14;
        ((HttpsURLConnection) (obj)).setHostnameVerifier(((javax.net.ssl.HostnameVerifier) (obj9)));
        ((HttpsURLConnection) (obj)).setSSLSocketFactory(sslsocketfactory2);
        return;
        obj4;
        obj3;
        JVM INSTR monitorexit ;
        obj17 = jsonexception1;
        i = i1;
        throw obj4;
_L26:
        obj17 = jsonexception1;
        i = k;
        jsonexception1.write(abyte0);
        obj17 = jsonexception1;
        i = k;
        i1 = k + abyte0.length;
        obj17 = jsonexception1;
        i = i1;
        jsonexception1.flush();
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        FileTransfer.access$300(((java.io.Closeable) (obj19)));
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        FileTransfer.access$300(jsonexception1);
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        val$context.currentOutputStream = null;
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        Log.d("FileTransfer", (new StringBuilder()).append("Sent ").append(i1).append(" of ").append(j).toString());
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        i = ((HttpURLConnection) (obj)).getResponseCode();
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        Log.d("FileTransfer", (new StringBuilder()).append("response code: ").append(i).toString());
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        Log.d("FileTransfer", (new StringBuilder()).append("response headers: ").append(((HttpURLConnection) (obj)).getHeaderFields()).toString());
        obj17 = null;
        jsonexception1 = FileTransfer.access$400(((java.net.URLConnection) (obj)));
        obj17 = jsonexception1;
        obj3 = val$context;
        obj17 = jsonexception1;
        obj3;
        JVM INSTR monitorenter ;
        if (!val$context.aborted)
        {
            break MISSING_BLOCK_LABEL_6137;
        }
        obj3;
        JVM INSTR monitorexit ;
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        val$context.currentInputStream = null;
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        FileTransfer.access$300(jsonexception1);
        synchronized (FileTransfer.access$600())
        {
            FileTransfer.access$600().remove(val$objectId);
        }
        if (obj == null || !val$trustEveryone || !val$useHttps) goto _L1; else goto _L29
_L29:
        obj = (HttpsURLConnection)obj;
        ((HttpsURLConnection) (obj)).setHostnameVerifier(((javax.net.ssl.HostnameVerifier) (obj5)));
        ((HttpsURLConnection) (obj)).setSSLSocketFactory(sslsocketfactory);
        return;
        obj;
        obj3;
        JVM INSTR monitorexit ;
        throw obj;
        val$context.currentInputStream = jsonexception1;
        obj3;
        JVM INSTR monitorexit ;
        obj17 = jsonexception1;
        obj3 = new ByteArrayOutputStream(Math.max(1024, ((HttpURLConnection) (obj)).getContentLength()));
        obj17 = jsonexception1;
        obj4 = new byte[1024];
_L31:
        obj17 = jsonexception1;
        k = jsonexception1.read(((byte []) (obj4)));
        if (k <= 0)
        {
            break; /* Loop/switch isn't completed */
        }
        obj17 = jsonexception1;
        ((ByteArrayOutputStream) (obj3)).write(((byte []) (obj4)), 0, k);
        if (true) goto _L31; else goto _L30
        jsonexception1;
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        val$context.currentInputStream = null;
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        FileTransfer.access$300(((java.io.Closeable) (obj17)));
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        throw jsonexception1;
        obj;
        obj7 = obj16;
        obj3 = obj11;
        obj4 = obj12;
        Log.e("FileTransfer", ((JSONException) (obj)).getMessage(), ((Throwable) (obj)));
        obj7 = obj16;
        obj3 = obj11;
        obj4 = obj12;
        val$context.sendPluginResult(new PluginResult(org.apache.cordova.api.atus.JSON_EXCEPTION));
        synchronized (FileTransfer.access$600())
        {
            FileTransfer.access$600().remove(val$objectId);
        }
        if (obj16 == null || !val$trustEveryone || !val$useHttps) goto _L1; else goto _L32
_L32:
        obj = (HttpsURLConnection)obj16;
        ((HttpsURLConnection) (obj)).setHostnameVerifier(((javax.net.ssl.HostnameVerifier) (obj11)));
        ((HttpsURLConnection) (obj)).setSSLSocketFactory(((javax.net.ssl.SSLSocketFactory) (obj12)));
        return;
        obj4;
        obj3;
        JVM INSTR monitorexit ;
        obj17 = jsonexception1;
        throw obj4;
_L30:
        obj17 = jsonexception1;
        obj19 = ((ByteArrayOutputStream) (obj3)).toString("UTF-8");
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        val$context.currentInputStream = null;
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        FileTransfer.access$300(jsonexception1);
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        Log.d("FileTransfer", "got response from server");
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        Log.d("FileTransfer", ((String) (obj19)).substring(0, Math.min(256, ((String) (obj19)).length())));
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        fileuploadresult.setResponseCode(i);
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        fileuploadresult.setResponse(((String) (obj19)));
        obj13 = obj;
        obj8 = obj5;
        sslsocketfactory1 = sslsocketfactory;
        obj14 = obj;
        k = j;
        obj9 = obj5;
        sslsocketfactory2 = sslsocketfactory;
        l = i1;
        obj16 = obj;
        obj11 = obj5;
        obj12 = sslsocketfactory;
        obj15 = obj;
        obj10 = obj5;
        sslsocketfactory3 = sslsocketfactory;
        obj7 = obj;
        obj3 = obj5;
        obj4 = sslsocketfactory;
        val$context.sendPluginResult(new PluginResult(org.apache.cordova.api.atus.OK, fileuploadresult.toJSONObject()));
        synchronized (FileTransfer.access$600())
        {
            FileTransfer.access$600().remove(val$objectId);
        }
        if (obj == null || !val$trustEveryone || !val$useHttps) goto _L1; else goto _L33
_L33:
        obj = (HttpsURLConnection)obj;
        ((HttpsURLConnection) (obj)).setHostnameVerifier(((javax.net.ssl.HostnameVerifier) (obj5)));
        ((HttpsURLConnection) (obj)).setSSLSocketFactory(sslsocketfactory);
        return;
        obj;
        obj3;
        JVM INSTR monitorexit ;
        throw obj;
        obj3;
        obj;
        JVM INSTR monitorexit ;
        throw obj3;
        obj3;
        obj;
        JVM INSTR monitorexit ;
        throw obj3;
        obj3;
        obj;
        JVM INSTR monitorexit ;
        throw obj3;
        Object obj1;
        obj1;
        obj7 = obj15;
        obj3 = obj10;
        obj4 = sslsocketfactory3;
        obj5 = FileTransfer.access$500(FileTransfer.CONNECTION_ERR, val$source, val$target, ((java.net.URLConnection) (obj15)));
        obj7 = obj15;
        obj3 = obj10;
        obj4 = sslsocketfactory3;
        Log.e("FileTransfer", ((JSONObject) (obj5)).toString(), ((Throwable) (obj1)));
        obj7 = obj15;
        obj3 = obj10;
        obj4 = sslsocketfactory3;
        val$context.sendPluginResult(new PluginResult(org.apache.cordova.api.atus.IO_EXCEPTION, ((JSONObject) (obj5))));
        synchronized (FileTransfer.access$600())
        {
            FileTransfer.access$600().remove(val$objectId);
        }
        if (obj15 == null || !val$trustEveryone || !val$useHttps) goto _L1; else goto _L34
_L34:
        obj2 = (HttpsURLConnection)obj15;
        ((HttpsURLConnection) (obj2)).setHostnameVerifier(((javax.net.ssl.HostnameVerifier) (obj10)));
        ((HttpsURLConnection) (obj2)).setSSLSocketFactory(sslsocketfactory3);
        return;
        obj3;
        obj2;
        JVM INSTR monitorexit ;
        throw obj3;
        obj2;
        synchronized (FileTransfer.access$600())
        {
            FileTransfer.access$600().remove(val$objectId);
        }
        if (obj7 != null && val$trustEveryone && val$useHttps)
        {
            obj6 = (HttpsURLConnection)obj7;
            ((HttpsURLConnection) (obj6)).setHostnameVerifier(((javax.net.ssl.HostnameVerifier) (obj3)));
            ((HttpsURLConnection) (obj6)).setSSLSocketFactory(((javax.net.ssl.SSLSocketFactory) (obj4)));
        }
        throw obj2;
        exception;
        obj6;
        JVM INSTR monitorexit ;
        throw exception;
        JSONException jsonexception;
        jsonexception;
          goto _L10
_L17:
        i = 1;
_L22:
        if (i == 0 && j != -1) goto _L36; else goto _L35
_L35:
        i = 1;
          goto _L23
    }

    questContext()
    {
        this$0 = final_filetransfer;
        val$context = questcontext;
        val$useHttps = flag;
        val$trustEveryone = flag1;
        val$url = url1;
        val$target = s;
        val$headers = jsonobject;
        val$params = jsonobject1;
        val$fileKey = s1;
        val$fileName = s2;
        val$mimeType = s3;
        val$source = s4;
        val$chunkedMode = flag2;
        val$objectId = String.this;
        super();
    }
}
